// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwC_rMqvtFLkhHYqYd8vPlPzoTwymQPb0',
    appId: '1:172168799326:web:4a21a1a6940de5968440cf',
    messagingSenderId: '172168799326',
    projectId: 'crossflow-e79b6',
    authDomain: 'crossflow-e79b6.firebaseapp.com',
    storageBucket: 'crossflow-e79b6.appspot.com',
    measurementId: 'G-4JTBTDCJ3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzuKZxz038yTyO9dG1lG5O5wyMDcSAsPE',
    appId: '1:172168799326:android:bb508f125f30c1df8440cf',
    messagingSenderId: '172168799326',
    projectId: 'crossflow-e79b6',
    storageBucket: 'crossflow-e79b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWRfEQZB-r79z7gT35n4USAyOoEtEPT1o',
    appId: '1:172168799326:ios:cebf41d5e2b2c4af8440cf',
    messagingSenderId: '172168799326',
    projectId: 'crossflow-e79b6',
    storageBucket: 'crossflow-e79b6.appspot.com',
    iosBundleId: 'com.example.crossflowMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWRfEQZB-r79z7gT35n4USAyOoEtEPT1o',
    appId: '1:172168799326:ios:cebf41d5e2b2c4af8440cf',
    messagingSenderId: '172168799326',
    projectId: 'crossflow-e79b6',
    storageBucket: 'crossflow-e79b6.appspot.com',
    iosBundleId: 'com.example.crossflowMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwC_rMqvtFLkhHYqYd8vPlPzoTwymQPb0',
    appId: '1:172168799326:web:8e8d83fd80f36a3f8440cf',
    messagingSenderId: '172168799326',
    projectId: 'crossflow-e79b6',
    authDomain: 'crossflow-e79b6.firebaseapp.com',
    storageBucket: 'crossflow-e79b6.appspot.com',
    measurementId: 'G-C6YNZRGM6J',
  );
}
